#!/bin/bash
# read input file named myin
# produce output file named myout with f = (x-3)^2

rm -rf myout

IFS=$'\n' read -d '' -r -a x < myin
a1=${x[0]}
a1="($(sed 's/[eE]+\{0,1\}/*10^/g' <<<"$a1"))"
a2=${x[1]}
a2="($(sed 's/[eE]+\{0,1\}/*10^/g' <<<"$a2"))" 
f=$(echo "($a1-2)*($a2-2)" | bc)
echo $f >>  myout


